### ISSUE TITLE
not able to pull energy out of the wooden solar power with any cable

### ISSUE THREAD

**Issue by Warbringer12** [BedrockLegends-Mods/WoodenUtilities#12]
![2020-10-23_22 08 56](https://user-images.githubusercontent.com/44590540/97068433-5fa97080-157c-11eb-9291-9657d2ed9539.png)

not connecting ;p

**Comment by pupnewfster** [comment]
https://github.com/lazyMods/WoodenUtilities/blob/master/src/main/java/com/lazy/woodenutilities/tiles/WoodenSolarPanelTileEntity.java#L180 is the wrong method to be overriding, see the javadocs: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/capabilities/ICapabilityProvider.java#L45

Edit: You also need to invalidate your lazy optional when the tile unloads.

None of https://github.com/lazyMods/WoodenUtilities/commit/23c55f60f36637e8a9db811150bbe99facc55da9 should be needed as mekanism has support for forge energy... the issue is that you don't expose that your tile actually supports forge energy.

**Comment by lazynessmind** [comment]
> Edit: You also need to invalidate your lazy optional when the tile unloads.

I always forget fc4b07e

> None of [23c55f6](https://github.com/lazyMods/WoodenUtilities/commit/23c55f60f36637e8a9db811150bbe99facc55da9) should be needed as mekanism has support for forge energy... the issue is that you don't expose that your tile actually supports forge energy.

pls can we forget I did that. 9b54b0a thanks 😢 

ALSO THANKS FOR THE HELP!
